name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22.2'

      - name: Display Go version
        run: go version

      - name: Display Go version
        run: go test -race -json ./... | go run github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter -output ctrf-report.json

      - name: Run CTRF annotations
        run: npx github-actions-ctrf ctrf-report.json
        if: always()
